name: 'Case Sensitivity Checker'
description: 'Check if there are any files or folders with same name differing only by case'
branding:
  icon: 'git-merge'
  color: 'gray-dark'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/checkcase
      shell: bash
