on: [push]

jobs:
  case-sensitivity_job:
    runs-on: ubuntu-latest
    name: check-file-case-sensitivity
    steps:
      # Checkout the source code so we have some files to look at.
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      # Run the actual merge conflict finder
      - name: Check Case Sensitivity
        uses: credfeto/action-case-checker@master
